### ISSUE TITLE
Commentaire en double

### ISSUE THREAD

**Issue by jfdarveau** [SerieBoldR/MethodesAnalyseSpatiale#11]
https://serieboldr.github.io/MethodesAnalyseSpatiale/07-RegressionSpatiales.html#sec-073:~:text=%23%23%20R%C3%A9sultats%20du%20mod%C3%A8le-,%23%20R%C3%A9sultats%20du%20mod%C3%A8les,-summary(Modele.SLX

**Comment by appariciop** [comment]
Merci de l'avoir relevé.
