### ISSUE TITLE
Mauvaise valeur (0 au lieu de 1)

### ISSUE THREAD

**Issue by Liammm100** [SerieBoldR/MethodesAnalyseSpatiale#17]
"Que ce soit avec les quadrats carrés ou hexagonaux, la valeur de p est égale à 0. Cela signifie que nous sommes 100 % certains que la distribution n’est pas dispersée."

Ici, pour être 100% certains que la distribution n'est pas dispersé, la valeur de p devrait être égale à 1.

**Comment by appariciop** [comment]
Merci de l'avoir signalé.
