### ISSUE TITLE
Incohérence entre la fonction décrite (lmSLX) et la fonction utilisée (errorsarlm)

### ISSUE THREAD

**Issue by jfdarveau** [SerieBoldR/MethodesAnalyseSpatiale#20]
Dans la section "7.1.2.3 Modèle SEM : autocorrélation spatiale sur le terme d’erreur" sous "Construction du modèle SAR dans R", la fonction mentionnée dans le teste est "lmSLX" alors que dans le code, la fonction utilisée est "errorsarlm".

**Comment by jfdarveau** [comment]
Duplicate of #18

**Comment by appariciop** [comment]
Corrigé, Merci de l'avoir signalé.
