### ISSUE TITLE
Incohérence avec la réponse à une question du quiz de révision du chapitre avec 

### ISSUE THREAD

**Issue by jfdarveau** [SerieBoldR/MethodesAnalyseSpatiale#21]
À la question "Dans un modèle SAR, l’autocorrélation est introduite au niveau de", la réponse considérée comme étant la bonne est "Variable dépendante" alors que dans la [section 7.1.2.2](https://serieboldr.github.io/MethodesAnalyseSpatiale/07-RegressionSpatiales.html#sec-07122), il est mentionné :

> Dans le modèle SAR (aussi appelé SAR-LAG), l’autocorrélation spatiale est intégrée au niveau de la variable indépendante [...].

**Comment by jfdarveau** [comment]
Duplicate of #18

**Comment by appariciop** [comment]
Corrigé. Merci de l'avoir signalé.
