### ISSUE TITLE
cv bandwidth

### ISSUE THREAD

**Issue by GurwenMeret** [SerieBoldR/MethodesAnalyseSpatiale#4]
Dans la partie 6.2.2, au 2ème bloc de code, dans la méthode bw_cv_likelihood_calc.mc():
le paramètre "bws" semble avoir été remplacé par "bw_range" et "bw_step" dans la documentation. 

bw_range = c(100,1200),
bw_step = 50

Le paramètre "adaptive" semble également avoir été enlevé et cause une erreur si on le laisse.

**Comment by appariciop** [comment]
Effectivement. Merci d'avoir signalé cette erreur.
