### ISSUE TITLE
Erreur Rook/Queen

### ISSUE THREAD

**Issue by jfdarveau** [SerieBoldR/MethodesAnalyseSpatiale#5]
Dans la section 2.2.4.2, la variable "Rook" est crée avec le paramètre "queen=TRUE" de la fonction "poly2nb".

`Rook <- poly2nb(Arrondissements, queen=TRUE)`

Autant dans la liste de points que dans le code.

**Comment by appariciop** [comment]
Effectivement. Corrigé! Merci de l'avoir signalé.
