### ISSUE TITLE
Variable "plocalMoranI" créé mais pas réutilisée

### ISSUE THREAD

**Issue by jfdarveau** [SerieBoldR/MethodesAnalyseSpatiale#7]
Dans la section 2.4.3, la variable "plocalMoranI" qui est créé dans le code pour obtenir la topologie de l’autocorrélation spatiale avec le I de Moran local n'est pas réutilisée.

Un peu plus bas, la partie de droite de l'assignation de cette variable est utilisée de nouveau.

```
Typologie <- case_when(
  localMoranI[, 5] < signif ~ Typologie,
  TRUE ~ "Non sign."
)
```

La variable pourrait être réutilisée pour éviter une duplication du code.

```
Typologie <- case_when(
  plocalMoranI < signif ~ Typologie,
  TRUE ~ "Non sign."
)
```

**Comment by appariciop** [comment]
Effectivement. Merci de l'avoir signalé. Corrigé!
