### ISSUE TITLE
Variable "coupures" créé mais pas réutilisée

### ISSUE THREAD

**Issue by jfdarveau** [SerieBoldR/MethodesAnalyseSpatiale#8]
Dans la section 2.4.1.2, la variable "coupures" qui est créé dans le code pour définir les intervalles n'est pas réutilisée.

La variable "classes.intervalles" est créé un peu plus loin avec la même liste de valeur.

**Comment by appariciop** [comment]
Effectivement. Merci de l'avoir signalé.

**Comment by appariciop** [comment]
Effectivement. Merci de l'avoir signalé.
